// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: write_request_server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteRequestServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *WriteRequestServer) Reset() {
	*x = WriteRequestServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_write_request_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRequestServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequestServer) ProtoMessage() {}

func (x *WriteRequestServer) ProtoReflect() protoreflect.Message {
	mi := &file_write_request_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequestServer.ProtoReflect.Descriptor instead.
func (*WriteRequestServer) Descriptor() ([]byte, []int) {
	return file_write_request_server_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRequestServer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteRequestServer) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type WriteReplyServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathHash []byte `protobuf:"bytes,1,opt,name=pathHash,proto3" json:"pathHash,omitempty"`
}

func (x *WriteReplyServer) Reset() {
	*x = WriteReplyServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_write_request_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteReplyServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReplyServer) ProtoMessage() {}

func (x *WriteReplyServer) ProtoReflect() protoreflect.Message {
	mi := &file_write_request_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReplyServer.ProtoReflect.Descriptor instead.
func (*WriteReplyServer) Descriptor() ([]byte, []int) {
	return file_write_request_server_proto_rawDescGZIP(), []int{1}
}

func (x *WriteReplyServer) GetPathHash() []byte {
	if x != nil {
		return x.PathHash
	}
	return nil
}

var File_write_request_server_proto protoreflect.FileDescriptor

var file_write_request_server_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x22, 0x46, 0x0a, 0x12, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x2e, 0x0a, 0x10, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x74, 0x68, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x70, 0x61, 0x74, 0x68, 0x48, 0x61, 0x73, 0x68, 0x32, 0x68, 0x0a, 0x0b, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x59, 0x0a, 0x05, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x12, 0x28, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x26, 0x2e, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x42, 0x1a, 0x5a, 0x18, 0x64, 0x63, 0x66, 0x73, 0x32, 0x2f, 0x44, 0x43,
	0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x57, 0x61, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_write_request_server_proto_rawDescOnce sync.Once
	file_write_request_server_proto_rawDescData = file_write_request_server_proto_rawDesc
)

func file_write_request_server_proto_rawDescGZIP() []byte {
	file_write_request_server_proto_rawDescOnce.Do(func() {
		file_write_request_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_write_request_server_proto_rawDescData)
	})
	return file_write_request_server_proto_rawDescData
}

var file_write_request_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_write_request_server_proto_goTypes = []interface{}{
	(*WriteRequestServer)(nil), // 0: write_request_server.WriteRequestServer
	(*WriteReplyServer)(nil),   // 1: write_request_server.WriteReplyServer
}
var file_write_request_server_proto_depIdxs = []int32{
	0, // 0: write_request_server.WriteServer.Write:input_type -> write_request_server.WriteRequestServer
	1, // 1: write_request_server.WriteServer.Write:output_type -> write_request_server.WriteReplyServer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_write_request_server_proto_init() }
func file_write_request_server_proto_init() {
	if File_write_request_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_write_request_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRequestServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_write_request_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteReplyServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_write_request_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_write_request_server_proto_goTypes,
		DependencyIndexes: file_write_request_server_proto_depIdxs,
		MessageInfos:      file_write_request_server_proto_msgTypes,
	}.Build()
	File_write_request_server_proto = out.File
	file_write_request_server_proto_rawDesc = nil
	file_write_request_server_proto_goTypes = nil
	file_write_request_server_proto_depIdxs = nil
}
