// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: write_request_server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WriteServerClient is the client API for WriteServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WriteServerClient interface {
	// Send a write request
	Write(ctx context.Context, in *WriteRequestServer, opts ...grpc.CallOption) (*WriteReplyServer, error)
}

type writeServerClient struct {
	cc grpc.ClientConnInterface
}

func NewWriteServerClient(cc grpc.ClientConnInterface) WriteServerClient {
	return &writeServerClient{cc}
}

func (c *writeServerClient) Write(ctx context.Context, in *WriteRequestServer, opts ...grpc.CallOption) (*WriteReplyServer, error) {
	out := new(WriteReplyServer)
	err := c.cc.Invoke(ctx, "/write_request_server.WriteServer/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriteServerServer is the server API for WriteServer service.
// All implementations must embed UnimplementedWriteServerServer
// for forward compatibility
type WriteServerServer interface {
	// Send a write request
	Write(context.Context, *WriteRequestServer) (*WriteReplyServer, error)
	mustEmbedUnimplementedWriteServerServer()
}

// UnimplementedWriteServerServer must be embedded to have forward compatible implementations.
type UnimplementedWriteServerServer struct {
}

func (UnimplementedWriteServerServer) Write(context.Context, *WriteRequestServer) (*WriteReplyServer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedWriteServerServer) mustEmbedUnimplementedWriteServerServer() {}

// UnsafeWriteServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WriteServerServer will
// result in compilation errors.
type UnsafeWriteServerServer interface {
	mustEmbedUnimplementedWriteServerServer()
}

func RegisterWriteServerServer(s grpc.ServiceRegistrar, srv WriteServerServer) {
	s.RegisterService(&WriteServer_ServiceDesc, srv)
}

func _WriteServer_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequestServer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteServerServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/write_request_server.WriteServer/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteServerServer).Write(ctx, req.(*WriteRequestServer))
	}
	return interceptor(ctx, in, info, handler)
}

// WriteServer_ServiceDesc is the grpc.ServiceDesc for WriteServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WriteServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "write_request_server.WriteServer",
	HandlerType: (*WriteServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _WriteServer_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "write_request_server.proto",
}
